# {{ ansible_managed }}
---
global:
  image:
     pullSecrets:
      - {{ docker.secret }}
  imagePullSecrets:
    - name: "{{ docker.secret }}"
  database:
    host: "{{ ansible_default_ipv4.address }}"
{% if postgres.database is defined %}
    name: "{{ postgres.database }}"
{% endif %}
{% if postgres.username is defined %}
    username: "{{ postgres.username }}"
{% endif %}
{% if postgres.password is defined %}
    password: "{{ postgres.password }}"
{% endif %}
{% if proxy is defined %}
{% if proxy.http is defined %}
  httpProxy: {{ proxy.http }}
{% endif %}
{% if proxy.http is defined %}
  httpsProxy: {{ proxy.https }}
{% endif %}
{% if proxy.dont_use_for is defined %}
  noProxy: "{{ proxy.dont_use_for | join(', ') }}"
{% endif %}
{% endif %}
{% if trustedCA_file is defined %}
  trusted:
    certificates: {{ lookup('ansible.builtin.file', trustedCA_file) | to_nice_json(indent=0) }}
{% elif (default_values.global.trusted.certificates is defined) and (default_values.global.trusted.certificates | length > 0) %}
  trusted:
    certificates: {{ default_values.global.trusted.certificates | to_nice_json(indent=0) }}
{% elif (default_values.trusted.certificates is defined) and (default_values.trusted.certificates | length > 0) %}
  trusted:
    certificates: {{ default_values.trusted.certificates | to_nice_json(indent=0) }}
{% endif %}
  keycloak:
{% if (czertainly is defined) and (czertainly.keycloak is defined) and czertainly.keycloak %}
    enabled: true
    # client secret must be set if keycloak is enabled
    clientSecret: "{{ keycloak_client_secret }}"
{% else %}
    enabled: false
{% endif %}
  hostName: "{{ ansible_fqdn }}"
  admin:
    username: "admin"
    password: "newgenerationtrustcare"
    name: "admin"
    surname: "admin"
    email: "admin@czertainly.local"

# this is needed only for KeyCloak
{% if (czertainly is defined) and (czertainly.keycloak is defined) and czertainly.keycloak %}
apiGateway:
  hostAliases:
    resolveInternalKeycloak: true
  trustedIps: "0.0.0.0/0,::/0"
{% endif %}

hostName: "{{ ansible_fqdn }}"
ingress:
  enabled: true
  certificate:
{% if (ingress is defined) and (ingress.certificate_file is defined) and (ingress.private_key_file is defined) %}
    source: external
{% else %}
    source: internal
{% endif %}

registerConnectors: true

commonCredentialProvider:
{% if (czertainly is defined) and (czertainly.commonCredentialProvider is defined) and czertainly.commonCredentialProvider %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

ejbcaNgConnector:
{% if (czertainly is defined) and (czertainly.ejbcaNgConnector is defined) and czertainly.ejbcaNgConnector %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

msAdcsConnector:
{% if (czertainly is defined) and (czertainly.msAdcsConnector is defined) and czertainly.msAdcsConnector %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

x509ComplianceProvider:
{% if (czertainly is defined) and (czertainly.x509ComplianceProvider is defined) and czertainly.x509ComplianceProvider %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

cryptosenseDiscoveryProvider:
{% if (czertainly is defined) and (czertainly.cryptosenseDiscoveryProvider is defined) and czertainly.cryptosenseDiscoveryProvider %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

networkDiscoveryProvider:
{% if (czertainly is defined) and (czertainly.cryptosenseDiscoveryProvider is defined) and czertainly.cryptosenseDiscoveryProvider %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

keystoreEntityProvider:
{% if (czertainly is defined) and (czertainly.keystoreEntityProvider is defined) and czertainly.keystoreEntityProvider %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

softwareCryptographyProvider:
{% if (czertainly is defined) and (czertainly.softwareCryptographyProvider is defined) and czertainly.softwareCryptographyProvider %}
  enabled: true
{% else %}
  enabled: false
{% endif %}

utilsService:
{% if (czertainly is defined) and (czertainly.utilsService is defined) and czertainly.utilsService %}
  enabled: true
{% else %}
  enabled: false
{% endif %}
